/// Mock data for courses
class MockCourseData {
  static List<Map<String, dynamic>> get courses => [
    {
      'id': 'cs101',
      'name': 'Introduction to Computer Science',
      'code': 'CS 101',
      'progress': 0.75,
      'professor': 'Jane Doe',
      'description': 'An introduction to computer science concepts, history, and problem solving.',
      'semester': '1st Semester',
      'academicYear': '2025-2026',
      'units': 3,
      'grade': 85.5,
      'schedule': 'MWF 9:00-10:00 AM',
      'room': 'CCS-101',
      'status': 'Ongoing',
    },
    {
      'id': 'math201',
      'name': 'Calculus I',
      'code': 'MATH 201',
      'progress': 0.60,
      'professor': 'John Smith',
      'description': 'Fundamental concepts of differential calculus.',
      'semester': '1st Semester',
      'academicYear': '2025-2026',
      'units': 3,
      'grade': 78.0,
      'schedule': 'TTH 10:00-11:30 AM',
      'room': 'MATH-205',
      'status': 'Ongoing',
    },
    {
      'id': 'phy151',
      'name': 'Physics I',
      'code': 'PHY 151',
      'progress': 0.85,
      'professor': 'Maria Garcia',
      'description': 'Introduction to mechanics, thermodynamics, and waves.',
      'semester': '1st Semester',
      'academicYear': '2025-2026',
      'units': 4,
      'grade': 92.0,
      'schedule': 'MWF 1:00-2:30 PM',
      'room': 'PHYS-Lab1',
      'status': 'Ongoing',
    },
    {
      'id': 'eng101',
      'name': 'English Composition',
      'code': 'ENG 101',
      'progress': 0.90,
      'professor': 'Sarah Johnson',
      'description': 'Academic writing and communication skills.',
      'semester': '1st Semester',
      'academicYear': '2025-2026',
      'units': 3,
      'grade': 88.5,
      'schedule': 'TTH 8:00-9:30 AM',
      'room': 'ENG-201',
      'status': 'Ongoing',
    },
    {
      'id': 'chem101',
      'name': 'General Chemistry',
      'code': 'CHEM 101',
      'progress': 0.45,
      'professor': 'Dr. Brown',
      'description': 'Basic principles of chemistry and chemical reactions.',
      'semester': '1st Semester',
      'academicYear': '2025-2026',
      'units': 4,
      'grade': 72.0,
      'schedule': 'MWF 3:00-4:30 PM',
      'room': 'CHEM-Lab2',
      'status': 'Ongoing',
    },
    {
      'id': 'pe101',
      'name': 'Physical Education',
      'code': 'PE 101',
      'progress': 1.0,
      'professor': 'Coach Wilson',
      'description': 'Physical fitness and health education.',
      'semester': '1st Semester',
      'academicYear': '2025-2026',
      'units': 2,
      'grade': 95.0,
      'schedule': 'TTH 4:00-5:00 PM',
      'room': 'Gymnasium',
      'status': 'Completed',
      'color': 0xFFFF9800,
      'exams': [
        {
          'id': 'pe101_midterm',
          'title': 'Midterm Practical Exam',
          'date': '2025-06-20',
          'status': 'completed',
          'score': 92.0,
        },
        {
          'id': 'pe101_final',
          'title': 'Final Practical Exam',
          'date': '2025-07-25',
          'status': 'upcoming',
          'score': null,
        },
      ],
    },
    {
      'id': 'math201',
      'code': 'MATH 201',
      'name': 'Advanced Mathematics',
      'description': 'Advanced mathematical concepts and applications.',
      'credits': 3,
      'professor': 'Dr. Roberto Cruz',
      'schedule': 'TTH 10:00-11:30 AM',
      'room': 'MATH-201',
      'progress': 75,
      'grade': 2.0,
      'status': 'Ongoing',
      'color': 0xFF9C27B0,
      'exams': [
        {
          'id': 'math201_midterm',
          'title': 'Midterm Examination',
          'date': '2025-06-15',
          'status': 'completed',
          'score': 88.0,
        },
        {
          'id': 'math201_final',
          'title': 'Final Examination',
          'date': '2025-07-20',
          'status': 'upcoming',
          'score': null,
        },
      ],
    },
    {
      'id': 'pe3',
      'code': 'PE 3',
      'name': 'Physical Education 3',
      'description': 'Team sports and fitness activities.',
      'credits': 2,
      'professor': 'Coach Miguel Torres',
      'schedule': 'W 3:00-5:00 PM',
      'room': 'Gymnasium',
      'progress': 95,
      'grade': 1.0,
      'status': 'Ongoing',
      'color': 0xFFE91E63,
      'exams': [
        {
          'id': 'pe3_midterm',
          'title': 'Midterm Skills Assessment',
          'date': '2025-06-18',
          'status': 'completed',
          'score': 94.0,
        },
        {
          'id': 'pe3_final',
          'title': 'Final Skills Assessment',
          'date': '2025-07-23',
          'status': 'upcoming',
          'score': null,
        },
      ],
    },
    {
      'id': 'rizal',
      'code': 'RIZAL',
      'name': 'Life and Works of Rizal',
      'description': 'Study of Jose Rizal\'s life, works, and contributions.',
      'credits': 3,
      'professor': 'Prof. Carmen dela Torre',
      'schedule': 'F 1:00-4:00 PM',
      'room': 'SAS-101',
      'progress': 88,
      'grade': 1.5,
      'status': 'Ongoing',
      'color': 0xFF607D8B,
      'exams': [
        {
          'id': 'rizal_midterm',
          'title': 'Midterm Examination',
          'date': '2025-06-22',
          'status': 'completed',
          'score': 87.0,
        },
        {
          'id': 'rizal_final',
          'title': 'Final Examination',
          'date': '2025-07-27',
          'status': 'upcoming',
          'score': null,
        },
      ],
    },
  ];

  static Map<String, dynamic> getCourseById(String id) {
    return courses.firstWhere(
      (course) => course['id'] == id,
      orElse: () => {},
    );
  }

  static List<Map<String, dynamic>> getCoursesBySemester(String semester) {
    // In a real app, this would filter by actual semester
    return courses;
  }
}
